import { cva, type VariantProps } from "class-variance-authority";
import type * as React from "react";
import { playClick } from "@/shared/lib/sound";
import { cn } from "@/shared/lib/utils";

// Generated by shadcn, then pruned to the variants and sizes Lobi actually
// renders (and no asChild/Slot — nothing composes Button over another
// element). Re-add variants from the registry as surfaces need them.
//
// Every button clicks audibly. Hooking it here rather than at each call site
// means new buttons get it for free and none can forget — and it's also the
// only place guaranteed to be inside a user gesture, which is what lets the
// AudioContext start at all (see shared/lib/sound.ts). Disabled buttons don't
// fire onClick, so they're silent for free.
export function Button({
  className,
  variant = "default",
  size = "default",
  onClick,
  ...props
}: React.ComponentProps<"button"> & VariantProps<typeof buttonVariants>) {
  function handleClick(event: React.MouseEvent<HTMLButtonElement>): void {
    playClick();
    onClick?.(event);
  }

  return (
    <button
      data-slot="button"
      data-variant={variant}
      data-size={size}
      onClick={handleClick}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  );
}

// ── Variants ─────────────────────────────────────────────────────────────────

export const buttonVariants = cva(
  "group/button inline-flex shrink-0 items-center justify-center rounded-full border border-transparent bg-clip-padding font-display text-sm font-medium tracking-tight whitespace-nowrap transition-all outline-none select-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 active:not-aria-[haspopup]:translate-y-px disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        // The one glowing thing on screen also lifts very slightly on hover —
        // the `active:translate-y-px` in the base class then reads as the
        // press that undoes it.
        default:
          "bg-primary text-primary-foreground shadow-glow-sm hover:-translate-y-px hover:bg-primary/90 hover:shadow-glow",
        outline:
          "border-border bg-background hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground dark:border-input dark:bg-input/30 dark:hover:bg-input/50",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-[color-mix(in_oklch,var(--secondary),var(--foreground)_5%)] aria-expanded:bg-secondary aria-expanded:text-secondary-foreground",
        ghost:
          "hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground dark:hover:bg-muted/50",
        destructive:
          "bg-destructive/10 text-destructive hover:bg-destructive/20 focus-visible:border-destructive/40 focus-visible:ring-destructive/20 dark:bg-destructive/20 dark:hover:bg-destructive/30 dark:focus-visible:ring-destructive/40",
      },
      size: {
        default:
          "h-8 gap-1.5 px-3 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2",
        xs: "h-6 gap-1 px-2.5 text-xs in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3",
        sm: "h-7 gap-1 px-3 text-[0.8rem] in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3.5",
        lg: "h-10 gap-2 px-5 text-base has-data-[icon=inline-end]:pr-3 has-data-[icon=inline-start]:pl-3",
        "icon-xs":
          "size-6 in-data-[slot=button-group]:rounded-lg [&_svg:not([class*='size-'])]:size-3",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  },
);
